# Generated by Django 5.0.4 on 2026-03-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
