# Generated by Django 5.0.4 on 2026-03-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_alter_booktag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('same_author', 'Тот же автор'), ('same_genre', 'Общие жанры'), ('same_series', 'Одна серия'), ('also_read', 'Также читали'), ('influenced_by', 'Повлияла на'), ('response_to', 'Ответ на'), ('similar_theme', 'Похожая тема'), ('sequel', 'Продолжение'), ('prequel', 'Приквел')], max_length=20)),
                ('is_auto', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='books.book')),
                ('book_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='books.book')),
            ],
            options={
                'unique_together': {('book_from', 'book_to', 'relation_type')},
            },
        ),
    ]
